version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=coinproce
      - MOLARIS_API_KEY=yeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjMzZDkzM2QyLTlmMTEtNGNhMC05OGEyLTczYzc2MDU4ODNkMiIsIm9yZ0lkIjoiNDE1NzczIiwidXNlcklkIjoiNDI3MzEyIiwidHlwZUlkIjoiN2JmMzU4ZTQtNDIwYi00MGQ2LTgzN2ItZGUyMjMyMGQ0MmYxIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3MzEzOTI5NjEsImV4cCI6NDg4NzE1Mjk2MX0.sU-fdjGYKM4Cvo7mBgYlxwRJ1xxMld64qUrwJTwgY-w
      - NODE_ENV=development
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=coinproce
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
